---
title: "Assignment_2"
output: html_document
date: "2022-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(tidyverse)
library(janitor)
library(ggplot2)
library(GGally)
library(rstatix)
library(pacman)
library(metafor)
library(flextable)
library(esc)
```

```{r}
path <- "C:/Users/caleb/OneDrive/Documents/Courses/2022 Semester 2/BIOL3207/BIOL3207_Assignment_2/Assignment_2/OA_activitydat_20190302_BIOL3207.csv"

  
data <- read_csv(path)
```

```{r}
#tidying up the data by removal irrelevant columns
drop <- c("comment", "loc")
data <- data[!(names(data) %in% drop)]
```

```{r}
#checking spelling of each species and treatment
categories1 <- unique(data$species)
categories1

categories2 <- unique(data$treatment)
categories2
```

```{r}
#summarising the data
dataft <- data %>%
  drop_na %>%
  group_by(species, treatment) %>%
  summarise(
    n = n(),
    mean = mean(activity),
    sd = sd(activity)
  )

flextable(dataft)
```

```{r}
#tidying data to fit into metadata layout
dataft[dataft == "control"] <- "ctrl"
dataft[dataft == "CO2"] <- "oa"
colnames(dataft)[1] <- "Species"

datalong <- pivot_longer(dataft, col = 3:5, names_to = "stat", values_to = "value")
datawide <- pivot_wider(datalong, names_from = c(treatment, stat), values_from = value, names_sep = ".")
datawide
```

```{r}
#import meta data from clark et al report
path2 <- "C:/Users/caleb/OneDrive/Documents/Courses/2022 Semester 2/BIOL3207/BIOL3207_Assignment_2/Assignment_2/clark_paper_data.csv"

data2 <- read_csv(path2)
data2
```

```{r}
#merge the two data sets to correspond with the larger data set
datacomb <- merge(data2, datawide)
datacomb
```

```{r}
path3 <- "C:/Users/caleb/OneDrive/Documents/Courses/2022 Semester 2/BIOL3207/BIOL3207_Assignment_2/Assignment_2/ocean_meta_data.csv"

data3 <- read_csv(path3)
data3
```

```{r}
datafinal <- rbind(data3, datacomb)
datafinal
```

```{r}
zr_data <- escalc(measure = "ROM", n1i = ctrl.n, n2i = oa.n, m1i = ctrl.mean, m2i = oa.mean, sd1i = ctrl.sd, sd2 = oa.sd, data = datafinal, var.names = c("Zr", "V_Zr"), append = TRUE)

zr_data
```

```{r}
which(datafinal$ctrl.mean <= 0)
which(datafinal$oa.mean <= 0)

which(datafinal$ctrl.mean <=0 & datafinal$oa.mean > 0 | datafinal$ctrl.mean > 0 & datafinal$oa.mean <= 0)
```

```{r}
dfeffect <- datafinal[!(datafinal$ctrl.mean <=0 & datafinal$oa.mean > 0 | datafinal$ctrl.mean > 0 & datafinal$oa.mean <= 0),]
dfeffect
```

```{r}
escalcfunc <- escalc(measure = "ROM", n1i = ctrl.n, n2i = oa.n, m1i = ctrl.mean, m2i = oa.mean, sd1i = ctrl.sd, sd2i = oa.sd, data = dftest)

dfeffect <- cbind(dfeffect, effect.size = escalcfunc$yi, sampling.variance = escalcfunc$vi)
dfeffect
```

```{r}
#I attempted to adjust the values of different signs but was unsuccessful and the code just wouldn't work. Furthermore, how is the ctrl group for reports that tested against a baseline not equal to close to 0? As such I left them removed from the escalc function
```

```{r}
names(dfeffect)[names(dfeffect) == "Behavioural metric"] <- "Behavioural.metric"
names(dfeffect)[names(dfeffect) == "Year (online)"] <- "Year.Pub"
```

```{r}
#meta-analytic model using the effect size and sampling variance of the escalc function. Random effect of the studies and within the studies using the species and behavioural metric within the species was used.
MA <- rma.mv(effect.size ~ 1, V = sampling.variance, method = "REML", random = list(~1 | Study/Species/Behavioural.metric), dfs = "contain", test = "t", data = dfeffect)
MA
```

THE...

```{r}
dfeffect %>% filter(dfeffect$sampling.variance > 0.00001) %>%
  funnel(x = dfeffect$effect.size, vi = dfeffect$sampling.variance, yaxis = "vinv", digits = 2, level = c(0.1, 0.05, 0.01), shade = c("white", "gray55", "gray75"), las = 1, xlab = "Correlation Coefficient (r)", atransf = tanh, legend = TRUE, ylim = c(0.1, 1000), xlim = c(-1, 1))
```

```{r}
dfeffect %>% filter(dfeffect$sampling.variance > 0.00001) %>%
  ggplot(aes(y = effect.size, x = Year.Pub, size = 1/sqrt(sampling.variance))) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = lm, col = "red", show.legend = FALSE) +
  labs(x = "Publication Year", y = "Effect Size", size = "Precision (1/SE)") +
  theme_classic()
```




























